
run_all = true #if true, this skips all other possible configurations below and just plots everything. I would not recommend right now

plot_specific_modules = true

specific_modules = [
    "BPix_BpI_SEC3_LAY14_LAY4_HV",
    "BPix_BmO_SEC4_LAY23_LAY3_HV",
    "FPix_BmO_D1_ROG2_RNG2_HV",
    "FPix_BmO_D1_ROG3_RNG1_HV",
    'BPix_BpI_SEC1_LAY14_LAY4_HV',
    'FPix_BmI_D3_ROG4_RNG1_HV',
    ]

# plot_BPix_LAY2 = false #not implemented yet

# The below is also not implemented yet, its coming soon though, stay tuned!

#time_range = ["2022-01-01 01:00:00", "2025-10-01 01:00:00"]


# BPix: #In the below lists, leave in the wildcard values you would like to query for
#   useBpix: true
#   position 1: ['BmI', 'BmO', 'BpI', 'BpO']
#   position 2: ['SEC1', 'SEC2', 'SEC3', 'SEC4', 'SEC5', 'SEC6', 'SEC7', 'SEC8'] # Sector
#   position 3: ['LAY14', 'LAY23'] # Layer
#   position 4: ['LAY1', 'LAY2', 'LAY3', 'LAY4'] #Layer number

# FPIX:
#   useFPix: false
#   position 1: ['BmI', 'BmO', 'BpI', 'BpO'] 
#   position 2: ['D1', 'D2', 'D3']
#   position 3: ['ROG1', 'ROG2', 'ROG3', 'ROG4']
#   position 4: ['RNG1', 'RNG2']

# This should be a list of all the modules (Power Groups?) in database:

#BPIX:

# ['BPix_BmI_SEC1_LAY14_LAY1_HV', 'BPix_BmI_SEC1_LAY14_LAY4_HV', 'BPix_BmI_SEC1_LAY23_LAY2_HV']
# ['BPix_BmI_SEC1_LAY23_LAY3_HV', 'BPix_BmI_SEC2_LAY14_LAY1_HV', 'BPix_BmI_SEC2_LAY14_LAY4_HV']
# ['BPix_BmI_SEC2_LAY23_LAY2_HV', 'BPix_BmI_SEC2_LAY23_LAY3_HV', 'BPix_BmI_SEC3_LAY14_LAY1_HV']
# ['BPix_BmI_SEC3_LAY14_LAY4_HV', 'BPix_BmI_SEC3_LAY23_LAY2_HV', 'BPix_BmI_SEC3_LAY23_LAY3_HV']
# ['BPix_BmI_SEC4_LAY14_LAY1_HV', 'BPix_BmI_SEC4_LAY14_LAY4_HV', 'BPix_BmI_SEC4_LAY23_LAY2_HV']
# ['BPix_BmI_SEC4_LAY23_LAY3_HV', 'BPix_BmI_SEC5_LAY14_LAY1_HV', 'BPix_BmI_SEC5_LAY14_LAY4_HV']
# ['BPix_BmI_SEC5_LAY23_LAY2_HV', 'BPix_BmI_SEC5_LAY23_LAY3_HV', 'BPix_BmI_SEC6_LAY14_LAY1_HV']
# ['BPix_BmI_SEC6_LAY14_LAY4_HV', 'BPix_BmI_SEC6_LAY23_LAY2_HV', 'BPix_BmI_SEC6_LAY23_LAY3_HV']
# ['BPix_BmI_SEC7_LAY14_LAY1_HV', 'BPix_BmI_SEC7_LAY23_LAY3_HV', 'BPix_BmI_SEC8_LAY14_LAY1_HV']
# ['BPix_BmI_SEC8_LAY14_LAY4_HV', 'BPix_BmI_SEC8_LAY23_LAY2_HV', 'BPix_BmI_SEC8_LAY23_LAY3_HV']
# ['BPix_BmO_SEC1_LAY14_LAY1_HV', 'BPix_BmO_SEC1_LAY14_LAY4_HV', 'BPix_BmO_SEC1_LAY23_LAY2_HV']
# ['BPix_BmO_SEC1_LAY23_LAY3_HV', 'BPix_BmO_SEC2_LAY14_LAY1_HV', 'BPix_BmO_SEC2_LAY14_LAY4_HV']
# ['BPix_BmO_SEC2_LAY23_LAY2_HV', 'BPix_BmO_SEC2_LAY23_LAY3_HV', 'BPix_BmO_SEC3_LAY14_LAY1_HV']
# ['BPix_BmO_SEC3_LAY14_LAY4_HV', 'BPix_BmO_SEC3_LAY23_LAY2_HV', 'BPix_BmO_SEC3_LAY23_LAY3_HV']
# ['BPix_BmO_SEC4_LAY14_LAY1_HV', 'BPix_BmO_SEC4_LAY14_LAY4_HV', 'BPix_BmO_SEC4_LAY23_LAY2_HV']
# ['BPix_BmO_SEC4_LAY23_LAY3_HV', 'BPix_BmO_SEC5_LAY14_LAY1_HV', 'BPix_BmO_SEC5_LAY14_LAY4_HV']
# ['BPix_BmO_SEC5_LAY23_LAY2_HV', 'BPix_BmO_SEC5_LAY23_LAY3_HV', 'BPix_BmO_SEC6_LAY14_LAY1_HV']
# ['BPix_BmO_SEC6_LAY14_LAY4_HV', 'BPix_BmO_SEC6_LAY23_LAY2_HV', 'BPix_BmO_SEC6_LAY23_LAY3_HV']
# ['BPix_BmO_SEC7_LAY14_LAY1_HV', 'BPix_BmO_SEC7_LAY14_LAY4_HV', 'BPix_BmO_SEC7_LAY23_LAY2_HV']
# ['BPix_BmO_SEC7_LAY23_LAY3_HV', 'BPix_BmO_SEC8_LAY14_LAY1_HV', 'BPix_BmO_SEC8_LAY14_LAY4_HV']
# ['BPix_BmO_SEC8_LAY23_LAY2_HV', 'BPix_BmO_SEC8_LAY23_LAY3_HV', 'BPix_BpI_SEC1_LAY14_LAY1_HV']
# ['BPix_BpI_SEC1_LAY14_LAY4_HV', 'BPix_BpI_SEC1_LAY23_LAY2_HV', 'BPix_BpI_SEC1_LAY23_LAY3_HV']
# ['BPix_BpI_SEC2_LAY14_LAY1_HV', 'BPix_BpI_SEC2_LAY14_LAY4_HV', 'BPix_BpI_SEC2_LAY23_LAY2_HV']
# ['BPix_BpI_SEC2_LAY23_LAY3_HV', 'BPix_BpI_SEC3_LAY14_LAY1_HV', 'BPix_BpI_SEC3_LAY14_LAY4_HV']
# ['BPix_BpI_SEC3_LAY23_LAY2_HV', 'BPix_BpI_SEC3_LAY23_LAY3_HV', 'BPix_BpI_SEC4_LAY14_LAY1_HV']
# ['BPix_BpI_SEC4_LAY14_LAY4_HV', 'BPix_BpI_SEC4_LAY23_LAY2_HV', 'BPix_BpI_SEC4_LAY23_LAY3_HV']
# ['BPix_BpI_SEC5_LAY14_LAY1_HV', 'BPix_BpI_SEC5_LAY14_LAY4_HV', 'BPix_BpI_SEC5_LAY23_LAY2_HV']
# ['BPix_BpI_SEC5_LAY23_LAY3_HV', 'BPix_BpI_SEC6_LAY14_LAY1_HV', 'BPix_BpI_SEC6_LAY14_LAY4_HV']
# ['BPix_BpI_SEC6_LAY23_LAY2_HV', 'BPix_BpI_SEC6_LAY23_LAY3_HV', 'BPix_BpI_SEC7_LAY14_LAY1_HV']
# ['BPix_BpI_SEC7_LAY14_LAY4_HV', 'BPix_BpI_SEC7_LAY23_LAY2_HV', 'BPix_BpI_SEC7_LAY23_LAY3_HV']
# ['BPix_BpI_SEC8_LAY14_LAY1_HV', 'BPix_BpI_SEC8_LAY14_LAY4_HV', 'BPix_BpI_SEC8_LAY23_LAY2_HV']
# ['BPix_BpI_SEC8_LAY23_LAY3_HV', 'BPix_BpO_SEC1_LAY14_LAY1_HV', 'BPix_BpO_SEC1_LAY14_LAY4_HV']
# ['BPix_BpO_SEC1_LAY23_LAY2_HV', 'BPix_BpO_SEC1_LAY23_LAY3_HV', 'BPix_BpO_SEC2_LAY14_LAY1_HV']
# ['BPix_BpO_SEC2_LAY14_LAY4_HV', 'BPix_BpO_SEC2_LAY23_LAY2_HV', 'BPix_BpO_SEC2_LAY23_LAY3_HV']
# ['BPix_BpO_SEC3_LAY14_LAY1_HV', 'BPix_BpO_SEC3_LAY14_LAY4_HV', 'BPix_BpO_SEC3_LAY23_LAY2_HV']
# ['BPix_BpO_SEC3_LAY23_LAY3_HV', 'BPix_BpO_SEC4_LAY14_LAY1_HV', 'BPix_BpO_SEC4_LAY14_LAY4_HV']
# ['BPix_BpO_SEC4_LAY23_LAY2_HV', 'BPix_BpO_SEC4_LAY23_LAY3_HV', 'BPix_BpO_SEC5_LAY14_LAY1_HV']
# ['BPix_BpO_SEC5_LAY14_LAY4_HV', 'BPix_BpO_SEC5_LAY23_LAY2_HV', 'BPix_BpO_SEC5_LAY23_LAY3_HV']
# ['BPix_BpO_SEC6_LAY14_LAY1_HV', 'BPix_BpO_SEC6_LAY14_LAY4_HV', 'BPix_BpO_SEC6_LAY23_LAY2_HV']
# ['BPix_BpO_SEC6_LAY23_LAY3_HV', 'BPix_BpO_SEC7_LAY14_LAY1_HV', 'BPix_BpO_SEC7_LAY14_LAY4_HV']
# ['BPix_BpO_SEC7_LAY23_LAY2_HV', 'BPix_BpO_SEC7_LAY23_LAY3_HV', 'BPix_BpO_SEC8_LAY14_LAY1_HV']
# ['BPix_BpO_SEC8_LAY14_LAY4_HV', 'BPix_BpO_SEC8_LAY23_LAY2_HV', 'BPix_BpO_SEC8_LAY23_LAY3_HV']

#FPIX:

# ['FPix_BmI_D1_ROG1_RNG1_HV', 'FPix_BmI_D1_ROG1_RNG2_HV', 'FPix_BmI_D1_ROG2_RNG1_HV']
# ['FPix_BmI_D1_ROG2_RNG2_HV', 'FPix_BmI_D1_ROG3_RNG1_HV', 'FPix_BmI_D1_ROG3_RNG2_HV']
# ['FPix_BmI_D1_ROG4_RNG1_HV', 'FPix_BmI_D1_ROG4_RNG2_HV', 'FPix_BmI_D2_ROG1_RNG1_HV']
# ['FPix_BmI_D2_ROG1_RNG2_HV', 'FPix_BmI_D2_ROG2_RNG1_HV', 'FPix_BmI_D2_ROG2_RNG2_HV']
# ['FPix_BmI_D2_ROG3_RNG1_HV', 'FPix_BmI_D2_ROG3_RNG2_HV', 'FPix_BmI_D2_ROG4_RNG1_HV']
# ['FPix_BmI_D2_ROG4_RNG2_HV', 'FPix_BmI_D3_ROG1_RNG1_HV', 'FPix_BmI_D3_ROG1_RNG2_HV']
# ['FPix_BmI_D3_ROG2_RNG1_HV', 'FPix_BmI_D3_ROG2_RNG2_HV', 'FPix_BmI_D3_ROG3_RNG1_HV']
# ['FPix_BmI_D3_ROG3_RNG2_HV', 'FPix_BmI_D3_ROG4_RNG1_HV', 'FPix_BmI_D3_ROG4_RNG2_HV']
# ['FPix_BmO_D1_ROG1_RNG1_HV', 'FPix_BmO_D1_ROG1_RNG2_HV', 'FPix_BmO_D1_ROG2_RNG1_HV']
# ['FPix_BmO_D1_ROG2_RNG2_HV', 'FPix_BmO_D1_ROG3_RNG1_HV', 'FPix_BmO_D1_ROG3_RNG2_HV']
# ['FPix_BmO_D1_ROG4_RNG1_HV', 'FPix_BmO_D1_ROG4_RNG2_HV', 'FPix_BmO_D2_ROG1_RNG1_HV']
# ['FPix_BmO_D2_ROG1_RNG2_HV', 'FPix_BmO_D2_ROG2_RNG1_HV', 'FPix_BmO_D2_ROG2_RNG2_HV']
# ['FPix_BmO_D2_ROG3_RNG1_HV', 'FPix_BmO_D2_ROG3_RNG2_HV', 'FPix_BmO_D2_ROG4_RNG1_HV']
# ['FPix_BmO_D2_ROG4_RNG2_HV', 'FPix_BmO_D3_ROG1_RNG1_HV', 'FPix_BmO_D3_ROG1_RNG2_HV']
# ['FPix_BmO_D3_ROG2_RNG1_HV', 'FPix_BmO_D3_ROG2_RNG2_HV', 'FPix_BmO_D3_ROG3_RNG1_HV']
# ['FPix_BmO_D3_ROG3_RNG2_HV', 'FPix_BmO_D3_ROG4_RNG1_HV', 'FPix_BmO_D3_ROG4_RNG2_HV']
# ['FPix_BpI_D1_ROG1_RNG1_HV', 'FPix_BpI_D1_ROG1_RNG2_HV', 'FPix_BpI_D1_ROG2_RNG1_HV']
# ['FPix_BpI_D1_ROG2_RNG2_HV', 'FPix_BpI_D1_ROG3_RNG1_HV', 'FPix_BpI_D1_ROG3_RNG2_HV']
# ['FPix_BpI_D1_ROG4_RNG1_HV', 'FPix_BpI_D1_ROG4_RNG2_HV', 'FPix_BpI_D2_ROG1_RNG1_HV']
# ['FPix_BpI_D2_ROG1_RNG2_HV', 'FPix_BpI_D2_ROG2_RNG1_HV', 'FPix_BpI_D2_ROG2_RNG2_HV']
# ['FPix_BpI_D2_ROG3_RNG1_HV', 'FPix_BpI_D2_ROG3_RNG2_HV', 'FPix_BpI_D2_ROG4_RNG1_HV']
# ['FPix_BpI_D2_ROG4_RNG2_HV', 'FPix_BpI_D3_ROG1_RNG1_HV', 'FPix_BpI_D3_ROG1_RNG2_HV']
# ['FPix_BpI_D3_ROG2_RNG1_HV', 'FPix_BpI_D3_ROG2_RNG2_HV', 'FPix_BpI_D3_ROG3_RNG1_HV']
# ['FPix_BpI_D3_ROG3_RNG2_HV', 'FPix_BpI_D3_ROG4_RNG1_HV', 'FPix_BpI_D3_ROG4_RNG2_HV']
# ['FPix_BpO_D1_ROG1_RNG1_HV', 'FPix_BpO_D1_ROG1_RNG2_HV', 'FPix_BpO_D1_ROG2_RNG1_HV']
# ['FPix_BpO_D1_ROG2_RNG2_HV', 'FPix_BpO_D1_ROG3_RNG1_HV', 'FPix_BpO_D1_ROG3_RNG2_HV']
# ['FPix_BpO_D1_ROG4_RNG1_HV', 'FPix_BpO_D1_ROG4_RNG2_HV', 'FPix_BpO_D2_ROG1_RNG1_HV']
# ['FPix_BpO_D2_ROG1_RNG2_HV', 'FPix_BpO_D2_ROG2_RNG1_HV', 'FPix_BpO_D2_ROG2_RNG2_HV']
# ['FPix_BpO_D2_ROG3_RNG1_HV', 'FPix_BpO_D2_ROG3_RNG2_HV', 'FPix_BpO_D2_ROG4_RNG1_HV']
# ['FPix_BpO_D2_ROG4_RNG2_HV', 'FPix_BpO_D3_ROG1_RNG1_HV', 'FPix_BpO_D3_ROG1_RNG2_HV']
# ['FPix_BpO_D3_ROG2_RNG1_HV', 'FPix_BpO_D3_ROG2_RNG2_HV', 'FPix_BpO_D3_ROG3_RNG1_HV']
# ['FPix_BpO_D3_ROG3_RNG2_HV', 'FPix_BpO_D3_ROG4_RNG1_HV', 'FPix_BpO_D3_ROG4_RNG2_HV']